# Voici un exemple presque complet de configuration pour un fichier
# mkdocs.yml utilisant pyodide-mkdocs-theme.

site_url: "http://semaine-speciale-casino.pages.dev"
site_name: "Semaine spéciale - Casino des mathématiques"
# site_description: "(optionnel)"
# repo_url: "(optionnel)"
# edit_uri_template: "(optionnel)"

# Copyright "CC BY-NC-SA"
copyright: |
  Aurélien Saudemont & Alan Morier


docs_dir: docs

nav:
  - "Accueil": index.md
# - ...

# Pour supprimer certains fichiers markdown de la navigation (pattern shell):
# not_in_nav: |
#   */**/*.md


# exclude_docs: Nécessite mkdocs 1.6+ pour fonctionner correctement. Sinon, vous pouvez
# utiliser le plugin mkdocs-exclude à la place.
# Ne surtout pas mettre de commentaires sur la ligne d'exclusion des fichiers python... !
# (exclure les fichiers python n'affecte pas les "python_libs")
exclude_docs: |
  **/*_REM.md
  **/*.py
  bac_a_sable.md

# Configuration du thème:
theme:
  name: pyodide-mkdocs-theme
  favicon: https://www.gymnase-etoy.ch/favicon.ico
  palette:
    primary: blue
  logo: /assets/logo-gnetoy.png
  custom_dir: overrides  
# features:
#   - navigation.instant    # Ne surtout pas activer cette option !



# Configuration minimale pour les plugins
plugins:
  - awesome-pages:          # Pas indispensable, mais... (pip install mkdocs-awesome-pages-plugin)
      collapse_single_pages: true

  - search

  - pyodide_macros:         # !!REQUIS!!
      build:
        python_libs:
          - turtle
        
        # Configuration pour les macros avec indentation
        macros_with_indents:
          - double_IDE
          - IDE_double

        # Configuration Pyodide
        # extra_pyodide_sections:
        #   - dessin
        #   - corr
        #   - env
        #   - tests
        #   - checks
        #   - grille
        #   - ignore
        
        # Configuration des IDEs
        ides_id_hash_mode: relative
      testing:
        include: site
      module_name: macros
      on_error_fail: true   # Fortement conseillé...
# - exclude-search:         # APRÈS le plugin search (pip install mkdocs-exclude-search)
#     exclude:              # Pour les fichiers inclus dans le build, que la recherche ne doit pas indexer
#       - bac_a_sable.md



markdown_extensions:

  # Extensions indispensables pour le thème:
  - md_in_html              # !!REQUIS!!
  - admonition              # !!REQUIS!! Blocs colorés:  !!! info "ma remarque"
  - attr_list               # !!REQUIS!! Un peu de CSS et des attributs HTML, ex: { #id .class style="display:none" }
  - pymdownx.details        # !!REQUIS!! Admonition: ??? -> peuvent se déplier ; ???+ -> peuvent se replier.
  - pymdownx.emoji:         # !!REQUIS!! Émojis:  :boom: (utilisé dans les terminaux)
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight      # !!REQUIS!! Coloration syntaxique du code
  - pymdownx.inlinehilite   # !!REQUIS!! Coloration syntaxique pour les "code spans": `#!python  code_python`
  - pymdownx.snippets:      # !!REQUIS!! Inclusion de fichiers externe.
      check_paths: true     # Fortement conseillé !
  - pymdownx.superfences:   # !!REQUIS!!
      custom_fences:        # (custom_fences: uniquement si vous comptez utiliser mermaid)
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.striphtml:
      strip_js_on_attributes: false     # !!REQUIS!!
      strip_attributes: ""              # !!REQUIS!!
  - pymdownx.arithmatex:    # !!REQUIS!! Pour LaTex
      generic: true
  # Extensions conseillées:
  - abbr
  - def_list                # Les listes de définition.
  - footnotes               # Notes[^1] de bas de page.  [^1]: ma note.
  - pymdownx.caret          # Passage ^^souligné^^ ou en ^exposant^.
  - pymdownx.mark           # Passage ==surligné==.
  - pymdownx.tilde          # Passage ~~barré~~ ou en ~indice~.
  - pymdownx.keys           # Touches du clavier:  ++ctrl+d++
  - pymdownx.tasklist:      # Cases à cocher  - [ ]  et - [x]
      custom_checkbox: false
      clickable_checkbox: true
  - pymdownx.tabbed:        # Volets glissants:  === "Mon volet"
      alternate_style: true # Meilleure compatibilité pour mobiles
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  # - toc:
  #     toc_depth: 0        # Si vous voulez supprimer la ToC (table of content) des pages



# Si mkdocs est lancé en mode strict (mkdocs ... --strict), les warnings lèveront une erreur
# en utilisant ces réglages :
validation:
  omitted_files: warn
  unrecognized_links: warn
extra_css:
  - https://cdn.jsdelivr.net/npm/tailwindcss@3.4.0/dist/tailwind.min.css

extra_javascript:
#   - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/react@18/umd/react.production.min.js
  - https://unpkg.com/react-dom@18/umd/react-dom.production.min.js
  - javascripts/blackjack-standalone.js
